labels:
  role: generic

steps:
  - name: aws-poweron
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - aws ec2 start-instances --region eu-north-1 --instance-ids i-07474e4fe80f14754 i-02bb3cbe63a2b3fef

when:
  - branch: main
    event: [tag]